services:
  coolmate-db:
    image: mysql:8.0
    container_name: coolmate-db
    ports:
      - "${DB_PORT}:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - coolmate-network
    restart: unless-stopped

networks:
  coolmate-network:
    driver: bridge

volumes:
  db-data:
    driver: local