server:
  member_port: "6336"
  movie_port: "8889"

database:
  host: localhost
  port: "3663"
  user: coolmate
  password: coolmate
  name: coolmate
  driver: mysql

logger:
  level: info
  format: console

jwt:
  secret_key: "toilacubeisathebestsecretkeyever1234567890"
  expiration_minutes: 60