server:
  member_port: "6336"
  movie_port: "8889"

database:
  host: mysql-db
  port: "3306"
  user: coolmate
  password: coolmate
  name: coolmate
  driver: mysql

logger:
  level: info
  format: console

jwt:
  secret_key: "591c35acdeff8456b1fa1031682133383fa8010c69304808fb5020c877294f9e"
  expiration_minutes: 60