services:
  caddy:
    image: caddy:latest
    container_name: coolmate-caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - coolmate-network

networks:
  coolmate-network:
    external: true
    name: coolmate-shared-network

volumes:
  caddy_data: {}