services:
  mysql-db:
    image: mysql:8.0
    container_name: coolmate-db
    ports:
      - "${DATABASE_PORT:-3663}:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - coolmate-network
    restart: unless-stopped

networks:
  coolmate-network:
    driver: bridge
    name: coolmate-shared-network

volumes:
  db-data:
    driver: local